[build]
  # Tell Netlify to run build in client folder
  base = "client"
  command = "npm run build"
  publish = "client/dist"
  functions = "server"

[functions]
  # If you need to specify settings for functions, like TS support, etc.
  node_bundler = "esbuild"
